import { getCliClient } from 'sanity/cli'

const client = getCliClient({ apiVersion: '2026-08-21' }).withConfig({ perspective: 'raw' })
const APPLY = process.argv.includes('--apply')
const RULESETS = [
  { _type: 'reference', _key: 'srd-2014', _ref: 'ruleset.srd-2014' },
  { _type: 'reference', _key: 'srd-2024', _ref: '86642d23-c52d-4577-adc1-214aab0f43e9' },
]
const ref = (id: string, key = id) => ({ _type: 'reference', _key: key, _ref: id })
type FeatureSeed = { level: number; name: string; description: string }

const progressionRows: Array<[number, number, string, string, string, string[]]> = [
  [1, 2, '1d6', '—', '—', ['Martial Arts', 'Unarmored Defense']],
  [2, 2, '1d6', '2', '+10 ft.', ["Monk's Focus", 'Unarmored Movement', 'Uncanny Metabolism']],
  [3, 2, '1d6', '3', '+10 ft.', ['Deflect Attacks', 'Monk Subclass']],
  [4, 2, '1d6', '4', '+10 ft.', ['Ability Score Improvement', 'Slow Fall']],
  [5, 3, '1d8', '5', '+10 ft.', ['Extra Attack', 'Stunning Strike']],
  [6, 3, '1d8', '6', '+15 ft.', ['Empowered Strikes', 'Subclass feature']],
  [7, 3, '1d8', '7', '+15 ft.', ['Evasion']],
  [8, 3, '1d8', '8', '+15 ft.', ['Ability Score Improvement']],
  [9, 4, '1d8', '9', '+15 ft.', ['Acrobatic Movement']],
  [10, 4, '1d8', '10', '+20 ft.', ['Heightened Focus', 'Self-Restoration']],
  [11, 4, '1d10', '11', '+20 ft.', ['Subclass feature']],
  [12, 4, '1d10', '12', '+20 ft.', ['Ability Score Improvement']],
  [13, 5, '1d10', '13', '+20 ft.', ['Deflect Energy']],
  [14, 5, '1d10', '14', '+25 ft.', ['Disciplined Survivor']],
  [15, 5, '1d10', '15', '+25 ft.', ['Perfect Focus']],
  [16, 5, '1d10', '16', '+25 ft.', ['Ability Score Improvement']],
  [17, 6, '1d12', '17', '+25 ft.', ['Subclass feature']],
  [18, 6, '1d12', '18', '+30 ft.', ['Superior Defense']],
  [19, 6, '1d12', '19', '+30 ft.', ['Epic Boon']],
  [20, 6, '1d12', '20', '+30 ft.', ['Body and Mind']],
]
const progression = progressionRows.map(([level, proficiencyBonus, martialArts, focusPoints, movement, featureNames]) => ({
  _type: 'classProgressionRow', _key: `monk-level-${level}`, level, proficiencyBonus,
  resources: [
    { _type: 'object', _key: 'martial-arts', name: 'Martial Arts', value: martialArts },
    { _type: 'object', _key: 'focus-points', name: 'Focus Points', value: focusPoints },
    { _type: 'object', _key: 'unarmored-movement', name: 'Unarmored Movement', value: movement },
  ], featureNames,
}))

const coreFeatures: FeatureSeed[] = [
  { level: 1, name: 'Martial Arts', description: 'While unarmed or wielding only Monk weapons—simple melee weapons and martial melee weapons with the Light property—and wearing no armor or Shield, you gain three benefits. Make one Unarmed Strike as a bonus action. Use the Martial Arts die shown in the Monk table for an Unarmed Strike or Monk weapon. Use Dexterity instead of Strength for attack and damage rolls and for the save DC of Grapple or Shove made through an Unarmed Strike.' },
  { level: 1, name: 'Unarmored Defense', description: 'While wearing no armor and wielding no Shield, your base Armor Class equals 10 + your Dexterity modifier + your Wisdom modifier.' },
  { level: 2, name: "Monk's Focus", description: 'You have Focus Points equal to your Monk level, restored after a short or long rest. Focus save DC = 8 + Wisdom modifier + proficiency bonus. Flurry of Blows spends 1 Focus Point to make two Unarmed Strikes as a bonus action. Patient Defense lets you Disengage as a bonus action, or spend 1 point to Disengage and Dodge together. Step of the Wind lets you Dash as a bonus action, or spend 1 point to Disengage and Dash together and double jump distance for the turn.' },
  { level: 2, name: 'Unarmored Movement', description: 'While wearing no armor and wielding no Shield, increase your speed by the amount shown in the Monk progression table: +10 feet at level 2, +15 at level 6, +20 at level 10, +25 at level 14, and +30 at level 18.' },
  { level: 2, name: 'Uncanny Metabolism', description: 'Once per long rest when you roll initiative, regain all expended Focus Points and regain hit points equal to your Monk level + one roll of your Martial Arts die.' },
  { level: 3, name: 'Deflect Attacks', description: 'When an attack hits you and includes bludgeoning, piercing, or slashing damage, use your reaction to reduce its total damage by 1d10 + Dexterity modifier + Monk level. If reduced to 0, spend 1 Focus Point to redirect the force. Choose a visible creature within 5 feet for a melee attack or within 60 feet and not behind total cover for a ranged attack. It makes a Dexterity save, taking two Martial Arts dice + Dexterity modifier of the triggering damage type on failure.' },
  { level: 3, name: 'Monk Subclass', description: 'Choose a Monk subclass. It grants features at Monk levels 3, 6, 11, and 17. Every Monk subclass in the archive is available under both the 2014 and 2024 rulesets.' },
  { level: 4, name: 'Ability Score Improvement', description: 'Gain the Ability Score Improvement feat or another feat for which you qualify. You gain this feature again at Monk levels 8, 12, and 16.' },
  { level: 4, name: 'Slow Fall', description: 'When you fall, use your reaction to reduce the falling damage you take by five times your Monk level.' },
  { level: 5, name: 'Extra Attack', description: 'Attack twice instead of once whenever you take the Attack action on your turn.' },
  { level: 5, name: 'Stunning Strike', description: 'Once per turn when you hit with a Monk weapon or Unarmed Strike, spend 1 Focus Point. The target makes a Constitution save. On failure, it is stunned until your next turn starts. On success, its speed is halved until then, and the next attack against it before then has advantage.' },
  { level: 6, name: 'Empowered Strikes', description: 'Whenever your Unarmed Strike deals damage, choose for it to deal force damage or its normal damage type.' },
  { level: 7, name: 'Evasion', description: 'When an effect permits a Dexterity save for half damage, take no damage on a success and half on a failure. You gain no benefit while incapacitated.' },
  { level: 8, name: 'Ability Score Improvement (8th Level)', description: 'Gain the Ability Score Improvement feat or another feat for which you qualify.' },
  { level: 9, name: 'Acrobatic Movement', description: 'While wearing no armor and wielding no Shield, move along vertical surfaces and across liquids during your turn without falling during the movement.' },
  { level: 10, name: 'Heightened Focus', description: 'Flurry of Blows makes three Unarmed Strikes instead of two. Spending Focus on Patient Defense also grants temporary hit points equal to two Martial Arts dice. Spending Focus on Step of the Wind lets you carry one willing Large or smaller creature within 5 feet along with your movement without provoking opportunity attacks.' },
  { level: 10, name: 'Self-Restoration', description: 'At the end of each of your turns, end the charmed, frightened, or poisoned condition on yourself. Forgoing food and drink does not give you Exhaustion.' },
  { level: 12, name: 'Ability Score Improvement (12th Level)', description: 'Gain the Ability Score Improvement feat or another feat for which you qualify.' },
  { level: 13, name: 'Deflect Energy', description: 'Deflect Attacks can now reduce an attack that deals any damage type, rather than only bludgeoning, piercing, or slashing damage.' },
  { level: 14, name: 'Disciplined Survivor', description: 'Gain proficiency in every saving throw. Whenever you fail a saving throw, spend 1 Focus Point to reroll it and use the new result.' },
  { level: 15, name: 'Perfect Focus', description: 'When you roll initiative and do not use Uncanny Metabolism, regain expended Focus Points until you have 4 if you currently have 3 or fewer.' },
  { level: 16, name: 'Ability Score Improvement (16th Level)', description: 'Gain the Ability Score Improvement feat or another feat for which you qualify.' },
  { level: 18, name: 'Superior Defense', description: 'At the start of your turn, spend 3 Focus Points to gain resistance to all damage except force damage for 1 minute or until you become incapacitated.' },
  { level: 19, name: 'Epic Boon', description: 'Gain an Epic Boon feat or another feat for which you qualify. Boon of Irresistible Offense is recommended.' },
  { level: 20, name: 'Body and Mind', description: 'Increase your Dexterity and Wisdom scores by 4, to a maximum of 25.' },
]

const ARTISAN_TOOLS_AND_INSTRUMENTS = [
  "Alchemist's supplies", "Brewer's supplies", "Calligrapher's supplies", "Carpenter's tools", "Cartographer's tools", "Cobbler's tools", "Cook's utensils", "Glassblower's tools", "Jeweler's tools", "Leatherworker's tools", "Mason's tools", "Painter's supplies", "Potter's tools", "Smith's tools", "Tinker's tools", "Weaver's tools", "Woodcarver's tools",
  'Bagpipes', 'Drum', 'Dulcimer', 'Flute', 'Lute', 'Lyre', 'Horn', 'Pan flute', 'Shawm', 'Viol',
]
const ELEMENTS_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-warrior-of-the-elements-3-elemental-attunement': { level: 3, name: 'Elemental Attunement', description: 'At the start of your turn, spend 1 Focus Point to imbue yourself with elemental energy for 10 minutes or until you become incapacitated. Reach: your Unarmed Strikes have 10 feet greater reach. Elemental Strikes: when an Unarmed Strike hits, make it deal acid, cold, fire, lightning, or thunder damage instead of its normal type. When it deals one of those types, force the target to make a Strength save; on failure, move it up to 10 feet toward or away from you.' },
  'feature-subclass-warrior-of-the-elements-3-manipulate-elements': { level: 3, name: 'Manipulate Elements', description: 'You know the Elementalism spell and use Wisdom as your spellcasting ability for it.' },
  'feature-subclass-warrior-of-the-elements-6-elemental-burst': { level: 6, name: 'Elemental Burst', description: 'As a Magic action, spend 2 Focus Points and choose a point within 120 feet. Elemental energy fills a 20-foot-radius sphere there; choose acid, cold, fire, lightning, or thunder damage. Each creature in the sphere makes a Dexterity save, taking three rolls of your Martial Arts die on failure or half as much on success.' },
  'feature-subclass-warrior-of-the-elements-11-stride-of-the-elements': { level: 11, name: 'Stride of the Elements', description: 'While Elemental Attunement is active, you have a flying speed and swimming speed equal to your speed.' },
  'feature-subclass-warrior-of-the-elements-17-elemental-epitome': { level: 17, name: 'Elemental Epitome', description: 'While Elemental Attunement is active, gain three benefits. Damage Resistance: choose resistance to acid, cold, fire, lightning, or thunder damage and change the choice at the start of each turn. Destructive Stride: when using Step of the Wind, increase speed by 20 feet for the turn; once per turn, each chosen creature takes one Martial Arts die of acid, cold, fire, lightning, or thunder damage when you enter a space within 5 feet of it. Empowered Strikes: once on each of your turns when an Unarmed Strike hits, deal one extra Martial Arts die of the strike’s damage type.' },
}
const MERCY_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-warrior-of-mercy-3-hand-of-harm': { level: 3, name: 'Hand of Harm', description: 'Once per turn when an Unarmed Strike hits a creature and deals damage, spend 1 Focus Point to deal extra necrotic damage equal to one roll of your Martial Arts die + your Wisdom modifier.' },
  'feature-subclass-warrior-of-mercy-3-hand-of-healing': { level: 3, name: 'Hand of Healing', description: 'As a Magic action, spend 1 Focus Point to touch a creature and restore hit points equal to one roll of your Martial Arts die + your Wisdom modifier. When using Flurry of Blows, replace one Unarmed Strike with Hand of Healing without spending a Focus Point for that healing.' },
  'feature-subclass-warrior-of-mercy-3-implements-of-mercy': { level: 3, name: 'Implements of Mercy', description: 'Gain proficiency in the Insight and Medicine skills and proficiency with the Herbalism Kit.' },
  'feature-subclass-warrior-of-mercy-6-physician-s-touch': { level: 6, name: "Physician's Touch", description: 'Hand of Harm can also give its target the poisoned condition until your next turn ends. Hand of Healing can also end one of these conditions on the healed creature: blinded, deafened, paralyzed, poisoned, or stunned.' },
  'feature-subclass-warrior-of-mercy-11-flurry-of-healing-and-harm': { level: 11, name: 'Flurry of Healing and Harm', description: 'When using Flurry of Blows, replace each Unarmed Strike with Hand of Healing without spending Focus Points for the healing. Alternatively, when a Flurry Unarmed Strike deals damage, use Hand of Harm with that strike without spending its Focus Point, still only once per turn. Use these benefits a combined number of times equal to your Wisdom modifier (minimum one), regaining all uses after a long rest.' },
  'feature-subclass-warrior-of-mercy-17-hand-of-ultimate-mercy': { level: 17, name: 'Hand of Ultimate Mercy', description: 'Once per long rest as a Magic action, touch the corpse of a creature that died within the past 24 hours and spend 5 Focus Points. It returns to life with hit points equal to 4d10 + your Wisdom modifier, and the blinded, deafened, paralyzed, poisoned, and stunned conditions are removed if it had them when it died.' },
}
const SHADOW_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-warrior-of-shadow-3-shadow-arts': { level: 3, name: 'Shadow Arts', description: 'Draw on the Shadowfell for three benefits. Darkness: spend 1 Focus Point to cast Darkness without components; you can see inside its area, and at the start of each turn while it persists, move its area to a space within 60 feet. Darkvision: gain 60-foot Darkvision, or increase existing Darkvision by 60 feet. Shadowy Figments: learn Minor Illusion and use Wisdom as its spellcasting ability.' },
  'feature-subclass-warrior-of-shadow-6-shadow-step': { level: 6, name: 'Shadow Step', description: 'While entirely within dim light or darkness, use a bonus action to teleport up to 60 feet to a visible unoccupied space also in dim light or darkness. You then have advantage on the next melee attack you make before the current turn ends.' },
  'feature-subclass-warrior-of-shadow-11-improved-shadow-step': { level: 11, name: 'Improved Shadow Step', description: 'When using Shadow Step, spend 1 Focus Point to ignore its requirement that you start and end in dim light or darkness. As part of the same bonus action, make an Unarmed Strike immediately after teleporting.' },
  'feature-subclass-warrior-of-shadow-17-cloak-of-shadows': { level: 17, name: 'Cloak of Shadows', description: 'As a Magic action while entirely within dim light or darkness, spend 3 Focus Points to shroud yourself for 1 minute, until incapacitated, or until ending a turn in bright light. While shrouded, you are invisible; you can move through occupied spaces as difficult terrain but are shunted to your last unoccupied space if you end there; and you may use Flurry of Blows without spending Focus Points.' },
}
const OPEN_HAND_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-warrior-of-the-open-hand-3-open-hand-technique': { level: 3, name: 'Open Hand Technique', description: 'Whenever an attack granted by Flurry of Blows hits a creature, impose one effect. Addle: it cannot make opportunity attacks until its next turn starts. Push: it makes a Strength save or is pushed up to 15 feet away from you. Topple: it makes a Dexterity save or gains the prone condition.' },
  'feature-subclass-warrior-of-the-open-hand-6-wholeness-of-body': { level: 6, name: 'Wholeness of Body', description: 'As a bonus action, roll your Martial Arts die and regain hit points equal to the roll + your Wisdom modifier, restoring at least 1 hit point. Use this feature a number of times equal to your Wisdom modifier (minimum one), regaining all uses after a long rest.' },
  'feature-subclass-warrior-of-the-open-hand-11-fleet-step': { level: 11, name: 'Fleet Step', description: 'Whenever you take a bonus action other than Step of the Wind, you can also use Step of the Wind immediately after that bonus action.' },
  'feature-subclass-warrior-of-the-open-hand-17-quivering-palm': { level: 17, name: 'Quivering Palm', description: 'When an Unarmed Strike hits a creature, spend 4 Focus Points to begin imperceptible vibrations lasting a number of days equal to your Monk level. End them with an action, or forgo one attack when taking the Attack action; you and the target must be on the same plane. The target makes a Constitution save, taking 10d12 force damage on failure or half on success. Only one creature can be affected at a time, and you may harmlessly end the vibrations without an action.' },
}
const ASTRAL_SELF_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-astral-self-3-arms-of-the-astral-self': { level: 3, name: 'Arms of the Astral Self', description: 'As a bonus action, spend 1 Focus Point (Ki Point) to summon spectral arms for 10 minutes, until incapacitated, or until you die. On summoning, each chosen visible creature within 10 feet makes a Dexterity save or takes force damage equal to two Martial Arts dice. While present, use Wisdom instead of Strength for Strength checks and saves; make Unarmed Strikes with the arms at 5 feet greater reach; and use Wisdom instead of Strength or Dexterity for their attack and damage rolls, which deal force damage.' },
  'feature-subclass-astral-self-6-visage-of-the-astral-self': { level: 6, name: 'Visage of the Astral Self', description: 'As a bonus action, or as part of the bonus action that summons your astral arms, spend 1 Focus Point (Ki Point) to summon a spectral visage for 10 minutes, until incapacitated, or until you die. Astral Sight sees normally through magical and nonmagical darkness to 120 feet. Wisdom of the Spirit grants advantage on Insight and Intimidation checks. Word of the Spirit lets only one visible creature within 60 feet hear your speech, or amplifies your voice to every creature within 600 feet.' },
  'feature-subclass-astral-self-11-body-of-the-astral-self': { level: 11, name: 'Body of the Astral Self', description: 'When both astral arms and visage are summoned, manifest the astral body without an action. Deflect Energy: when taking acid, cold, fire, force, lightning, or thunder damage, use your reaction to reduce it by 1d10 + Wisdom modifier, with a minimum reduction of 1. Empowered Arms: once on each of your turns when the astral arms hit, deal one additional Martial Arts die of damage.' },
  'feature-subclass-astral-self-17-awakened-astral-self': { level: 17, name: 'Awakened Astral Self', description: 'As a bonus action, spend 5 Focus Points (Ki Points) to summon and awaken your astral arms, visage, and body for 10 minutes, until incapacitated, or until you die. Armor of the Spirit grants +2 AC. Astral Barrage lets you make three attacks instead of two whenever Extra Attack is used, provided every attack is made with the astral arms.' },
}
const ASCENDANT_DRAGON_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-ascendant-dragon-3-draconic-disciple': { level: 3, name: 'Draconic Disciple', description: 'Channel draconic power through three benefits. Draconic Presence: after failing an Intimidation or Persuasion check, use your reaction to reroll it; once this reroll turns failure into success, regain it after a long rest. Draconic Strike: when an Unarmed Strike damages a target, change its damage type to acid, cold, fire, lightning, or poison. Tongue of Dragons: learn to speak, read, and write Draconic or one other language of your choice.' },
  'feature-subclass-ascendant-dragon-3-breath-of-the-dragon': { level: 3, name: 'Breath of the Dragon', description: 'When taking the Attack action, replace one attack with draconic energy in a 20-foot cone or a 30-foot-long, 5-foot-wide line. Choose acid, cold, fire, lightning, or poison damage. Each creature in the area makes a Dexterity save against your Focus (Ki) save DC, taking two Martial Arts dice on failure or half on success; this becomes three Martial Arts dice at level 11. Use this feature a number of times equal to your proficiency bonus per long rest. With no uses remaining, spend 2 Focus Points (Ki Points) to use it again.' },
  'feature-subclass-ascendant-dragon-6-wings-unfurled': { level: 6, name: 'Wings Unfurled', description: 'When using Step of the Wind, unfurl spectral draconic wings that last until your turn ends. While present, they grant a flying speed equal to your walking speed. Use this feature a number of times equal to your proficiency bonus, regaining all expended uses after a long rest.' },
  'feature-subclass-ascendant-dragon-11-aspect-of-the-wyrm': { level: 11, name: 'Aspect of the Wyrm', description: 'As a bonus action, create a 10-foot draconic aura for 1 minute and choose one effect. Frightful Presence: on activation and as a bonus action on later turns, choose a creature in the aura; it makes a Wisdom save against your Focus (Ki) save DC or becomes frightened of you for 1 minute, repeating the save at the end of each turn. Resistance: choose acid, cold, fire, lightning, or poison; you and allies in the aura have resistance to that damage. Once used, regain the aura after a long rest, or spend 3 Focus Points (Ki Points) to create it again.' },
  'feature-subclass-ascendant-dragon-17-ascendant-aspect': { level: 17, name: 'Ascendant Aspect', description: 'Your draconic spirit reaches its peak. Augment Breath: spend 1 Focus Point (Ki Point) when using Breath of the Dragon to make it a 60-foot cone or a 90-foot-long, 5-foot-wide line dealing four Martial Arts dice on a failed save or half on success. Blindsight: gain blindsight to 10 feet, perceiving anything not behind total cover, including invisible creatures that are not hidden. Explosive Fury: when activating Aspect of the Wyrm, choose visible creatures in the aura; each makes a Dexterity save against your Focus (Ki) save DC or takes 3d10 acid, cold, fire, lightning, or poison damage, chosen by you.' },
}
const DRUNKEN_MASTER_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-drunken-master-3-bonus-proficiencies': { level: 3, name: 'Bonus Proficiencies', description: 'Gain proficiency in the Performance skill and with brewer’s supplies if you do not already have those proficiencies. Your martial art combines combat training with a dancer’s precision and a jester’s antics.' },
  'feature-subclass-drunken-master-3-drunken-technique': { level: 3, name: 'Drunken Technique', description: 'Whenever you use Flurry of Blows, you also gain the benefit of the Disengage action and your walking speed increases by 10 feet until the current turn ends.' },
  'feature-subclass-drunken-master-6-tipsy-sway': { level: 6, name: 'Tipsy Sway', description: 'Your sudden swaying grants two benefits. Leap to Your Feet: when prone, stand by spending 5 feet of movement instead of half your speed. Redirect Attack: when a creature misses you with a melee attack roll, spend 1 Focus Point (Ki Point) and use your reaction to cause that attack to hit a creature of your choice other than the attacker that you can see within 5 feet of you.' },
  'feature-subclass-drunken-master-11-drunkard-s-luck': { level: 11, name: 'Drunkard’s Luck', description: 'When you make an ability check, attack roll, or saving throw with disadvantage, spend 2 Focus Points (Ki Points) to cancel disadvantage for that roll.' },
  'feature-subclass-drunken-master-17-intoxicated-frenzy': { level: 17, name: 'Intoxicated Frenzy', description: 'When using Flurry of Blows, make up to three additional attacks with it, for up to five Flurry of Blows attacks in total, provided that every Flurry of Blows attack you make that turn targets a different creature.' },
}
const FOUR_ELEMENTS_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-four-elements-3-disciple-of-the-elements': { level: 3, name: 'Disciple of the Elements', description: 'Learn Elemental Attunement and one other elemental discipline of your choice. Each discipline specifies the Focus Point (Ki Point) cost to use it. Whenever you learn a new discipline, you may replace one discipline you already know with another. Casting Elemental Spells: a discipline that casts a spell uses that spell’s casting time and rules but requires no material components. From Monk level 5, spend additional points to raise a discipline spell’s level by 1 per additional point when the spell has a higher-level effect. The maximum total points spent on one spell, including its base cost, is 3 at levels 5–8, 4 at levels 9–12, 5 at levels 13–16, and 6 at levels 17–20.' },
  'feature-subclass-four-elements-6-extra-elemental-discipline': { level: 6, name: 'Extra Elemental Discipline', description: 'Learn one additional elemental discipline of your choice. When learning it, you may also replace one elemental discipline you already know with a different discipline.' },
  'feature-subclass-four-elements-11-extra-elemental-discipline': { level: 11, name: 'Extra Elemental Discipline', description: 'Learn one additional elemental discipline of your choice. When learning it, you may also replace one elemental discipline you already know with a different discipline. Your maximum total Focus Point (Ki Point) expenditure on a single discipline spell is 4 through level 12 and becomes 5 at level 13.' },
  'feature-subclass-four-elements-17-extra-elemental-discipline': { level: 17, name: 'Extra Elemental Discipline', description: 'Learn one additional elemental discipline of your choice. When learning it, you may also replace one elemental discipline you already know with a different discipline. Your maximum total Focus Point (Ki Point) expenditure on a single discipline spell becomes 6.' },
}
const KENSEI_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-kensei-3-path-of-the-kensei': { level: 3, name: 'Path of the Kensei', description: 'Gain four benefits. Kensei Weapons: choose one melee and one ranged simple or martial weapon lacking the Heavy and Special properties; a longbow is also valid. Gain proficiency with them, and they become Monk weapons. Choose one additional eligible weapon at levels 6, 11, and 17. Agile Parry: after making an Unarmed Strike as part of your Attack action while holding a melee Kensei weapon, gain +2 AC until your next turn starts while holding it and not incapacitated. Kensei’s Shot: as a bonus action, ranged Kensei weapon hits deal an extra 1d4 of the weapon’s damage type until the turn ends. Way of the Brush: gain proficiency with calligrapher’s supplies or painter’s supplies.' },
  'feature-subclass-kensei-6-one-with-the-blade': { level: 6, name: 'One with the Blade', description: 'Extend your Focus into your Kensei weapons and choose another eligible weapon type as a Kensei weapon. Magic Kensei Weapons: their attacks count as magical for overcoming resistance and immunity to nonmagical attacks and damage. Deft Strike: once on each of your turns when a Kensei weapon hits, spend 1 Focus Point (Ki Point) to deal extra damage equal to one Martial Arts die.' },
  'feature-subclass-kensei-11-sharpen-the-blade': { level: 11, name: 'Sharpen the Blade', description: 'Choose another eligible weapon type as a Kensei weapon. As a bonus action, spend up to 3 Focus Points (Ki Points) and touch one Kensei weapon to grant it a bonus to attack and damage rolls equal to the points spent. The bonus lasts for 1 minute or until you use this feature again. It has no effect on a magic weapon that already grants a bonus to attack and damage rolls.' },
  'feature-subclass-kensei-17-unerring-accuracy': { level: 17, name: 'Unerring Accuracy', description: 'Choose another eligible weapon type as a Kensei weapon. Once on each of your turns, when you miss with an attack roll using a Monk weapon, reroll that attack roll.' },
}
const LONG_DEATH_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-long-death-3-touch-of-death': { level: 3, name: 'Touch of Death', description: 'When you reduce a creature within 5 feet of you to 0 Hit Points, extract its fading vitality and gain temporary Hit Points equal to your Wisdom modifier + your Monk level, with a minimum of 1 temporary Hit Point.' },
  'feature-subclass-long-death-6-hour-of-reaping': { level: 6, name: 'Hour of Reaping', description: 'As an action, unsettle those around you with a soul touched by death. Each creature within 30 feet that can see you must succeed on a Wisdom saving throw or become frightened of you until your next turn ends.' },
  'feature-subclass-long-death-11-mastery-of-death': { level: 11, name: 'Mastery of Death', description: 'When you are reduced to 0 Hit Points, spend 1 Focus Point (Ki Point), requiring no action, to have 1 Hit Point instead.' },
  'feature-subclass-long-death-17-touch-of-the-long-death': { level: 17, name: 'Touch of the Long Death', description: 'As an action, touch one creature within 5 feet and spend 1 to 10 Focus Points (Ki Points). The target makes a Constitution saving throw, taking 2d10 necrotic damage for each point spent on failure or half as much damage on success.' },
}
const WAY_MERCY_ID = 'subclass-way-of-mercy'
const WAY_MERCY_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-way-of-mercy-3-implements-of-mercy': { level: 3, name: 'Implements of Mercy', description: 'Gain proficiency in the Insight and Medicine skills and with the Herbalism Kit. You also gain a special mask whose appearance you choose; traditional forms include a raven, a blank white face, a crying or laughing visage, a skull, or a butterfly.' },
  'feature-subclass-way-of-mercy-3-hands-of-healing': { level: 3, name: 'Hands of Healing', description: 'As an action, spend 1 Focus Point (Ki Point) to touch a creature and restore Hit Points equal to one roll of your Martial Arts die + your Wisdom modifier. When using Flurry of Blows, replace one Unarmed Strike with this healing without spending a point for it.' },
  'feature-subclass-way-of-mercy-3-hands-of-harm': { level: 3, name: 'Hands of Harm', description: 'Once per turn when an Unarmed Strike hits a creature, spend 1 Focus Point (Ki Point) to deal extra necrotic damage equal to one roll of your Martial Arts die + your Wisdom modifier.' },
  'feature-subclass-way-of-mercy-6-physician-s-touch': { level: 6, name: 'Physician’s Touch', description: 'Hands of Healing can also end one disease or one of these conditions affecting the healed creature: blinded, deafened, paralyzed, poisoned, or stunned. Hands of Harm can also give its target the poisoned condition until your next turn ends.' },
  'feature-subclass-way-of-mercy-11-flurry-of-healing-and-harm': { level: 11, name: 'Flurry of Healing and Harm', description: 'When using Flurry of Blows, replace each Unarmed Strike with Hands of Healing without spending points for the healing. In addition, when an Unarmed Strike made through Flurry of Blows hits, use Hands of Harm with that strike without spending its point. Hands of Harm remains limited to once per turn.' },
  'feature-subclass-way-of-mercy-17-hand-of-ultimate-mercy': { level: 17, name: 'Hand of Ultimate Mercy', description: 'Once per long rest as an action, touch the corpse of a creature that died within the past 24 hours and spend 5 Focus Points (Ki Points). It returns to life with Hit Points equal to 4d10 + your Wisdom modifier. If it died while blinded, deafened, paralyzed, poisoned, or stunned, it returns without those conditions.' },
}
const ASCENDANT_DRAGON_UA_ID = 'subclass-ascendant-dragon-ua'
const ASCENDANT_DRAGON_UA_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-ascendant-dragon-ua-3-draconic-disciple': { level: 3, name: 'Draconic Disciple', description: 'Gain three draconic benefits. When an Unarmed Strike damages a target, change its damage type to acid, cold, fire, lightning, or poison. Learn to speak, read, and write Draconic if you cannot already. After failing an Intimidation or Persuasion check, use your reaction to reroll it; once this reroll turns failure into success, regain it after a long rest.' },
  'feature-subclass-ascendant-dragon-ua-3-breath-of-the-dragon': { level: 3, name: 'Breath of the Dragon', description: 'When taking the Attack action, replace one attack with draconic energy in a 20-foot cone or a 30-foot-long, 5-foot-wide line. Choose acid, cold, fire, lightning, or poison damage. Each creature in the area makes a Dexterity save against your Focus (Ki) save DC, taking two Martial Arts dice on failure or half on success; this becomes three Martial Arts dice at level 11. Use this feature a number of times equal to your proficiency bonus per long rest. With no uses remaining, spend 1 Focus Point (Ki Point) to use it again.' },
  'feature-subclass-ascendant-dragon-ua-6-wings-unfurled': { level: 6, name: 'Wings Unfurled', description: 'When using Step of the Wind, unfurl spectral draconic wings until your turn ends and gain a flying speed equal to your walking speed. Use this feature a number of times equal to your proficiency bonus per long rest. With no uses remaining, spend 1 additional Focus Point (Ki Point) when activating Step of the Wind to use it again.' },
  'feature-subclass-ascendant-dragon-ua-11-aspect-of-the-wyrm': { level: 11, name: 'Aspect of the Wyrm', description: 'As a bonus action, create a 30-foot aura for 1 minute and choose acid, cold, fire, lightning, or poison damage. You and allies within the aura have resistance to the chosen type. When you or an ally in the aura is hit by an attack made by another creature within the aura, the hit target may use its reaction to deal one Martial Arts die of the chosen damage to the attacker. Once used, regain the aura after a long rest, or spend 4 Focus Points (Ki Points) to use it again.' },
  'feature-subclass-ascendant-dragon-ua-17-ascendant-aspect': { level: 17, name: 'Ascendant Aspect', description: 'Gain blindsight to 30 feet, perceiving anything not behind total cover, including invisible creatures that are not hidden. When Breath of the Dragon damages a creature, it takes one Martial Arts die of the breath’s damage type at the start of each turn, then repeats the save at the end of that turn to end the effect. When activating Aspect of the Wyrm, choose visible creatures in the aura; each takes 4d10 acid, cold, fire, lightning, or poison damage, chosen by you.' },
}
const ASTRAL_SELF_UA_ID = 'subclass-astral-self-ua'
const ASTRAL_SELF_UA_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-astral-self-ua-3-arms-of-the-astral-self': { level: 3, name: 'Arms of the Astral Self', description: 'As a bonus action, spend 2 Focus Points (Ki Points) to summon spectral arms for 10 minutes. While present, use Wisdom instead of Strength for Strength checks and saving throws. The arms are Monk weapons with 10-foot reach, deal radiant or necrotic damage chosen by you, and can use Wisdom instead of Strength or Dexterity for attack and damage rolls. Immediately after taking the Attack action with the arms, make one arm attack as a bonus action; this becomes two bonus attacks at level 11 and three at level 17.' },
  'feature-subclass-astral-self-ua-6-visage-of-the-astral-self': { level: 6, name: 'Visage of the Astral Self', description: 'As a bonus action, or as part of summoning the astral arms, spend 1 Focus Point (Ki Point) to summon a spectral visage for 10 minutes. Wisdom of the Spirit grants advantage on Insight and Intimidation checks. Astral Sight lets you see normally through magical and nonmagical darkness to 120 feet.' },
  'feature-subclass-astral-self-ua-11-awakening-of-the-astral-self': { level: 11, name: 'Awakening of the Astral Self', description: 'While both astral arms and visage are summoned, gain three benefits. Deflect Energy: when taking acid, cold, fire, lightning, or force damage, use your reaction to reduce it by 1d10 + your Wisdom modifier + your Monk level. Empowered Arms: once on each of your turns when the arms hit, deal one extra Martial Arts die. Word of the Spirit: speak privately to one visible creature within 30 feet, or amplify your voice to all creatures within 600 feet.' },
  'feature-subclass-astral-self-ua-17-complete-astral-self': { level: 17, name: 'Complete Astral Self', description: 'As a bonus action, spend 10 Focus Points (Ki Points) to summon the complete astral self for 10 minutes. Armor of the Spirit grants +2 AC while you are not incapacitated. Astral Barrage lets Extra Attack make three astral-arm attacks instead of two. Ki Consumption: when a creature within 10 feet is reduced to 0 Hit Points, use your reaction to regain Focus Points (Ki Points) equal to your Wisdom modifier, with a minimum of 1.' },
}
const KENSEI_UA_ID = 'subclass-kensei-ua'
const KENSEI_UA_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-kensei-ua-3-path-of-the-kensei': { level: 3, name: 'Path of the Kensei', description: 'Gain proficiency with three martial weapons of your choice; every martial weapon with which you are proficient is a Kensei weapon for you. When wielding a Kensei weapon, choose Strength or Dexterity for its attack and damage rolls and choose whether to replace its damage die with your Martial Arts die. After taking the Attack action and hitting with a Kensei weapon, use a bonus action to pummel: the hit target and every other target you hit with that weapon as part of the Attack each take an extra 1d4 bludgeoning damage. After making an Unarmed Strike as part of the Attack action while holding a Kensei weapon, gain +2 AC until your next turn starts while holding it and not incapacitated.' },
  'feature-subclass-kensei-ua-6-one-with-the-blade': { level: 6, name: 'One with the Blade', description: 'Gain two benefits. Magic Weapons: attacks with Kensei weapons count as magical for overcoming resistance and immunity to nonmagical attacks and damage. Precise Strike: as a bonus action, choose one visible creature within 30 feet; your next weapon attack against it during the current turn adds twice your proficiency bonus to the attack roll instead of the normal bonus. Once used, regain Precise Strike after a short or long rest.' },
  'feature-subclass-kensei-ua-11-sharpen-the-blade': { level: 11, name: 'Sharpen the Blade', description: 'As a bonus action, spend up to 3 Focus Points (Ki Points) and touch a weapon. While you wield it, that weapon gains a bonus to attack and damage rolls equal to the points spent. The bonus lasts for 1 minute.' },
  'feature-subclass-kensei-ua-17-unerring-accuracy': { level: 17, name: 'Unerring Accuracy', description: 'Once on each of your turns, reroll one weapon attack roll you make that misses.' },
}
const WAY_MERCY_UA_ID = 'subclass-way-of-mercy-ua'
const WAY_MERCY_UA_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-way-of-mercy-ua-3-implements-of-mercy': { level: 3, name: 'Implements of Mercy', description: 'Gain proficiency in either Insight or Medicine, chosen by you, and gain proficiency with both the Herbalism Kit and Poisoner’s Kit. You may also wear a special mask whose traditional forms include a raven, a blank white face, a crying or laughing visage, a skull, or a butterfly.' },
  'feature-subclass-way-of-mercy-ua-3-hands-of-healing': { level: 3, name: 'Hands of Healing', description: 'As an action, spend 1 Focus Point (Ki Point) to touch a creature and restore Hit Points equal to one roll of your Martial Arts die + your Wisdom modifier. When using Flurry of Blows, replace one Unarmed Strike with this healing without spending its point cost.' },
  'feature-subclass-way-of-mercy-ua-3-hands-of-harm': { level: 3, name: 'Hands of Harm', description: 'Once on each of your turns when an Unarmed Strike hits a creature, spend 1 Focus Point (Ki Point) to deal extra necrotic damage equal to one Martial Arts die. If the creature is incapacitated or poisoned, the extra damage instead equals three Martial Arts dice.' },
  'feature-subclass-way-of-mercy-ua-6-noxious-aura': { level: 6, name: 'Noxious Aura', description: 'As a bonus action, spend 1 Focus Point (Ki Point) to create a toxic aura extending 5 feet from you but not through total cover. It lasts 1 minute, until you are incapacitated, or until you dismiss it without an action. Ranged attacks against you have disadvantage. Any other creature starting its turn in the aura makes a Constitution save or becomes poisoned until your next turn ends and takes poison damage equal to your Wisdom modifier, with a minimum of 0.' },
  'feature-subclass-way-of-mercy-ua-11-healing-technique': { level: 11, name: 'Healing Technique', description: 'When Hands of Healing restores Hit Points to a creature, also end one disease or one of these conditions affecting it: blinded, deafened, paralyzed, or poisoned.' },
  'feature-subclass-way-of-mercy-ua-17-hand-of-mercy': { level: 17, name: 'Hand of Mercy', description: 'As an action, touch a creature, spend 4 Focus Points (Ki Points), and force a Constitution saving throw, which the creature may willingly fail. On failure, it enters suspended animation for a number of days equal to your Monk level or until you end it without an action. It is paralyzed, immune to all damage, and its curses, diseases, and poisons are suspended; outward inspection and divination perceive it as dead. Only one creature can be under this effect at a time.' },
}
const TRANQUILITY_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-tranquility-3-path-of-tranquility': { level: 3, name: 'Path of Tranquility', description: 'Cast Sanctuary on yourself without material components; it lasts up to 8 hours and has a saving throw DC of 8 + your proficiency bonus + your Wisdom modifier. A creature that succeeds on the save is immune to this use for 1 hour. Once cast this way, you cannot cast it this way again for 1 minute.' },
  'feature-subclass-tranquility-3-healing-hands': { level: 3, name: 'Healing Hands', description: 'Gain a healing pool equal to ten times your Monk level that replenishes after a long rest. As an action, touch a creature and spend any remaining points to restore that many Hit Points. Instead, spend 5 pool points per disease cured or poison neutralized, resolving multiple effects in one use by paying separately. When using Flurry of Blows, replace one Unarmed Strike with Healing Hands. This feature has no effect on Undead or Constructs.' },
  'feature-subclass-tranquility-6-emissary-of-peace': { level: 6, name: 'Emissary of Peace', description: 'Gain advantage on Charisma checks made in good faith to calm violent emotions or counsel peace; this does not apply when Deception or Intimidation proficiency would apply. Also gain proficiency in either Performance or Persuasion, chosen by you.' },
  'feature-subclass-tranquility-11-douse-the-flames-of-war': { level: 11, name: 'Douse the Flames of War', description: 'As an action, touch a creature and force a Wisdom saving throw against DC 8 + your proficiency bonus + your Wisdom modifier; a creature missing any Hit Points automatically succeeds. On failure, for 1 minute it cannot attack or cast spells that deal damage or force a saving throw. The effect ends if it is attacked, damaged, or forced to save, or if it witnesses any of those events affecting one of its allies.' },
  'feature-subclass-tranquility-17-anger-of-a-gentle-soul': { level: 17, name: 'Anger of a Gentle Soul', description: 'When you see a creature reduce another creature to 0 Hit Points, use your reaction to gain a bonus equal to your Monk level on every damage roll you make against the aggressor until your next turn ends. Once used, regain this feature after a short or long rest.' },
}
const ADDITIVE_MONK_SUBCLASS_IDS = [WAY_MERCY_ID, ASCENDANT_DRAGON_UA_ID, ASTRAL_SELF_UA_ID, KENSEI_UA_ID, WAY_MERCY_UA_ID]
const WAY_OPEN_HAND_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-open-hand-3-open-hand-technique': { level: 3, name: 'Open Hand Technique', description: 'Whenever an attack granted by Flurry of Blows hits a creature, impose one effect on that target: it makes a Dexterity saving throw or is knocked prone; it makes a Strength saving throw and, on failure, you push it up to 15 feet away; or it cannot take reactions until your next turn ends.' },
  'feature-subclass-open-hand-6-wholeness-of-body': { level: 6, name: 'Wholeness of Body', description: 'As an action, regain Hit Points equal to three times your Monk level. Once used, regain this feature after finishing a long rest.' },
  'feature-subclass-open-hand-11-tranquility': { level: 11, name: 'Tranquility', description: 'At the end of a long rest, gain the effect of the Sanctuary spell, which lasts until your next long rest starts but can end early as normal. Its saving throw DC equals 8 + your Wisdom modifier + your proficiency bonus.' },
  'feature-subclass-open-hand-17-quivering-palm': { level: 17, name: 'Quivering Palm', description: 'When an Unarmed Strike hits a creature, spend 3 Focus Points (Ki Points) to begin imperceptible vibrations lasting a number of days equal to your Monk level. Use an action to end them while you and the target are on the same plane. The target makes a Constitution saving throw; on failure, it is reduced to 0 Hit Points, and on success, it takes 10d10 necrotic damage. Only one creature can be affected at a time, and you may harmlessly end the vibrations without an action.' },
}
const WAY_SHADOW_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-shadow-3-shadow-arts': { level: 3, name: 'Shadow Arts', description: 'As an action, spend 2 Focus Points (Ki Points) to cast Darkness, Darkvision, Pass without Trace, or Silence without providing material components. You also learn the Minor Illusion cantrip if you do not already know it.' },
  'feature-subclass-shadow-6-shadow-step': { level: 6, name: 'Shadow Step', description: 'While in dim light or darkness, use a bonus action to teleport up to 60 feet to an unoccupied space you can see that is also in dim light or darkness. You then have advantage on the first melee attack you make before the turn ends.' },
  'feature-subclass-shadow-11-cloak-of-shadows': { level: 11, name: 'Cloak of Shadows', description: 'While in an area of dim light or darkness, use an action to become invisible. The invisibility lasts until you make an attack, cast a spell, or enter an area of bright light.' },
  'feature-subclass-shadow-17-opportunist': { level: 17, name: 'Opportunist', description: 'Whenever a creature within 5 feet of you is hit by an attack made by a creature other than you, use your reaction to make one melee attack against the creature that was hit.' },
}
const SUN_SOUL_SOURCE = "Sword Coast Adventurer's Guide / Xanathar's Guide to Everything"
const SUN_SOUL_FEATURES: Record<string, FeatureSeed> = {
  'feature-subclass-way-of-the-sun-soul-3-radiant-sun-bolt': { level: 3, name: 'Radiant Sun Bolt', description: 'Gain a ranged spell attack usable with the Attack action. It has a range of 30 feet; you are proficient with it; it uses Dexterity for attack and damage rolls; and it deals radiant damage equal to your Martial Arts die. When you take the Attack action and use this attack as part of it, spend 1 Focus Point (Ki Point) to make two Radiant Sun Bolt attacks as a bonus action. After gaining Extra Attack, use the bolt for any attacks made as part of the Attack action.' },
  'feature-subclass-way-of-the-sun-soul-6-searing-arc-strike': { level: 6, name: 'Searing Arc Strike', description: 'Immediately after taking the Attack action on your turn, spend 2 Focus Points (Ki Points) to cast Burning Hands as a bonus action. Spend additional points to raise the spell’s level by 1 for each additional point. The maximum total points spent on the spell, including its base cost of 2, equals half your Monk level.' },
  'feature-subclass-way-of-the-sun-soul-11-searing-sunburst': { level: 11, name: 'Searing Sunburst', description: 'As an action, create an orb of light and hurl it at a point within 150 feet, where it erupts in a 20-foot-radius sphere. Each creature in the sphere makes a Constitution saving throw or takes 2d6 radiant damage; a creature behind opaque total cover need not save. Spend up to 3 Focus Points (Ki Points) to increase the damage by 2d6 per point.' },
  'feature-subclass-way-of-the-sun-soul-17-sun-shield': { level: 17, name: 'Sun Shield', description: 'You are wreathed in a magical aura that sheds bright light for 30 feet and dim light for another 30 feet. Extinguish or restore the light as a bonus action. While it shines, when a creature hits you with a melee attack, use your reaction to deal radiant damage to that creature equal to 5 + your Wisdom modifier.' },
}
const OLD_FEATURE_IDS = Array.from({ length: 5 }, (_, index) => `feature-class-monk-feature-${index}`)
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
function featureDocument(seed: FeatureSeed, index: number) {
  const slug = slugify(seed.name)
  const id = `feature-monk-${seed.level}-${slug}`
  return { id, document: { _id: id, _type: 'feature', name: seed.name, slug: { _type: 'slug', current: `monk-${seed.level}-${slug}`.slice(0, 96) }, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete Monk mechanic supplied from the 2024 Player’s Handbook progression and enabled for both archive rulesets by owner request.' }, reference: ref(id, `${seed.level}-${slug}-${index}`) }
}

async function run() {
  const current = await client.fetch<any>(`*[_id == "class-monk"][0]{source,isHomebrew,hitDie,primaryAbility,savingThrows,"featureIds":features[]._ref,"subclassIds":subclasses[]._ref}`)
  const allowedFeatureIds = new Set([...OLD_FEATURE_IDS, ...coreFeatures.map((seed) => `feature-monk-${seed.level}-${slugify(seed.name)}`)])
  const additiveSubclassCount = current?.subclassIds?.filter((id: string) => ADDITIVE_MONK_SUBCLASS_IDS.includes(id)).length || 0
  if (!current || current.source !== 'Official' || current.isHomebrew || current.hitDie !== 8 || current.primaryAbility.join(',') !== 'DEX,WIS' || current.savingThrows.join(',') !== 'STR,DEX' || current.featureIds.some((id: string) => !allowedFeatureIds.has(id)) || current.subclassIds.length !== 14 + additiveSubclassCount) throw new Error(`Refusing to update an unexpected Monk record: ${JSON.stringify(current)}`)

  const monkSubclasses = await client.fetch<any[]>(`*[_type=="subclass" && (parentClassId=="monk" || parentClass._ref=="class-monk")]{_id,isHomebrew,"featureIds":features[]._ref}`)
  const subclassFeatureIds = [...new Set(monkSubclasses.flatMap((subclass) => subclass.featureIds || []))]
  const coreFeatureIds = coreFeatures.map((seed) => `feature-monk-${seed.level}-${slugify(seed.name)}`)
  let tx = client.transaction()
  const featureRefs = coreFeatures.map((seed, index) => { const built = featureDocument(seed, index); tx = tx.createOrReplace(built.document as any); return built.reference })
  const tranquilityFeatureRefs = Object.entries(TRANQUILITY_FEATURES).map(([id, seed]) => {
    tx = tx.createOrReplace({ _id: id, _type: 'feature', name: seed.name, slug: { _type: 'slug', current: id.replace(/^feature-subclass-/, '') }, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of Tranquility playtest mechanic enabled for both archive rulesets by owner request.' } as any)
    return ref(id, id.replace(/^feature-subclass-tranquility-/, ''))
  })
  const wayMercyFeatureRefs = Object.entries(WAY_MERCY_FEATURES).map(([id, seed]) => {
    tx = tx.createOrReplace({ _id: id, _type: 'feature', name: seed.name, slug: { _type: 'slug', current: id.replace(/^feature-subclass-/, '') }, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of Mercy mechanic enabled for both archive rulesets by owner request.' } as any)
    return ref(id, id.replace(/^feature-subclass-way-of-mercy-/, ''))
  })
  tx = tx.createOrReplace({
    _id: WAY_MERCY_ID, _type: 'subclass', version: 1, name: 'Way of Mercy', slug: { _type: 'slug', current: 'way-of-mercy' },
    parentClassId: 'monk', parentClass: ref('class-monk', 'monk'),
    description: 'Monks of the Way of Mercy manipulate life force to aid the suffering and bring swift ends to those beyond help, walking as masked physicians and faceless agents of life and death.',
    features: wayMercyFeatureRefs, source: 'Official', sourceBook: "Tasha's Cauldron of Everything", edition: 'Both', rulesets: RULESETS,
    isHomebrew: false, isSpellcaster: false, versionNotes: 'Complete supplied Way of Mercy mechanics enabled for both archive rulesets by owner request.',
  } as any)
  const ascendantDragonUaFeatureRefs = Object.entries(ASCENDANT_DRAGON_UA_FEATURES).map(([id, seed]) => {
    tx = tx.createOrReplace({ _id: id, _type: 'feature', name: seed.name, slug: { _type: 'slug', current: id.replace(/^feature-subclass-/, '') }, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Unearthed Arcana Ascendant Dragon playtest mechanic enabled for both archive rulesets by owner request.' } as any)
    return ref(id, id.replace(/^feature-subclass-ascendant-dragon-ua-/, ''))
  })
  tx = tx.createOrReplace({
    _id: ASCENDANT_DRAGON_UA_ID, _type: 'subclass', version: 1, name: 'Way of the Ascendant Dragon (UA)', slug: { _type: 'slug', current: 'way-of-the-ascendant-dragon-ua' },
    parentClassId: 'monk', parentClass: ref('class-monk', 'monk'),
    description: 'This Unearthed Arcana playtest tradition alters a Monk’s inner Focus to resonate with draconic might, empowering strikes and breath, manifesting wings, and surrounding allies with a retaliatory draconic aura. Its origin might be a dragon mentor, an ancient monastery, meditation near a dragon’s lair, a Draconic scroll, close observation of a dragon, or a transformative dream.',
    features: ascendantDragonUaFeatureRefs, source: 'Official', sourceBook: 'Unearthed Arcana 75 - Subclasses, Part 5', edition: 'Both', rulesets: RULESETS,
    isHomebrew: false, isSpellcaster: false, versionNotes: 'Preserved as a distinct official playtest subclass because its mechanics differ materially from the finalized Fizban’s version.',
  } as any)
  const astralSelfUaFeatureRefs = Object.entries(ASTRAL_SELF_UA_FEATURES).map(([id, seed]) => {
    tx = tx.createOrReplace({ _id: id, _type: 'feature', name: seed.name, slug: { _type: 'slug', current: id.replace(/^feature-subclass-/, '') }, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Unearthed Arcana Astral Self playtest mechanic enabled for both archive rulesets by owner request.' } as any)
    return ref(id, id.replace(/^feature-subclass-astral-self-ua-/, ''))
  })
  tx = tx.createOrReplace({
    _id: ASTRAL_SELF_UA_ID, _type: 'subclass', version: 1, name: 'Way of the Astral Self (UA)', slug: { _type: 'slug', current: 'way-of-the-astral-self-ua' },
    parentClassId: 'monk', parentClass: ref('class-monk', 'monk'),
    description: 'This Unearthed Arcana playtest tradition treats inner Focus as the Monk’s true astral form, manifesting radiant or necrotic arms, a supernatural visage, heightened energy defenses, and ultimately a complete astral body that consumes released life energy.',
    features: astralSelfUaFeatureRefs, source: 'Official', sourceBook: 'Unearthed Arcana 60 - Barbarian and Monk', edition: 'Both', rulesets: RULESETS,
    isHomebrew: false, isSpellcaster: false, versionNotes: 'Preserved as a distinct official playtest subclass because its mechanics differ materially from the finalized Tasha’s version.',
  } as any)
  const kenseiUaFeatureRefs = Object.entries(KENSEI_UA_FEATURES).map(([id, seed]) => {
    tx = tx.createOrReplace({ _id: id, _type: 'feature', name: seed.name, slug: { _type: 'slug', current: id.replace(/^feature-subclass-/, '') }, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Unearthed Arcana Kensei playtest mechanic enabled for both archive rulesets by owner request.' } as any)
    return ref(id, id.replace(/^feature-subclass-kensei-ua-/, ''))
  })
  tx = tx.createOrReplace({
    _id: KENSEI_UA_ID, _type: 'subclass', version: 1, name: 'Kensei (UA)', slug: { _type: 'slug', current: 'kensei-ua' },
    parentClassId: 'monk', parentClass: ref('class-monk', 'monk'),
    description: 'This Unearthed Arcana playtest tradition treats martial weapons as extensions of the body and tools of artistic expression, combining broad weapon mastery, precise focused attacks, supernatural augmentation, and unerring accuracy.',
    features: kenseiUaFeatureRefs, source: 'Official', sourceBook: 'Unearthed Arcana 24 - Monk', edition: 'Both', rulesets: RULESETS,
    isHomebrew: false, isSpellcaster: false, versionNotes: 'Preserved as a distinct official playtest subclass because its mechanics differ materially from the finalized Xanathar’s version.',
  } as any)
  const wayMercyUaFeatureRefs = Object.entries(WAY_MERCY_UA_FEATURES).map(([id, seed]) => {
    tx = tx.createOrReplace({ _id: id, _type: 'feature', name: seed.name, slug: { _type: 'slug', current: id.replace(/^feature-subclass-/, '') }, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Unearthed Arcana Way of Mercy playtest mechanic enabled for both archive rulesets by owner request.' } as any)
    return ref(id, id.replace(/^feature-subclass-way-of-mercy-ua-/, ''))
  })
  tx = tx.createOrReplace({
    _id: WAY_MERCY_UA_ID, _type: 'subclass', version: 1, name: 'Way of Mercy (UA)', slug: { _type: 'slug', current: 'way-of-mercy-ua' },
    parentClassId: 'monk', parentClass: ref('class-monk', 'monk'),
    description: 'This Unearthed Arcana playtest tradition manipulates life force to heal the suffering or grant a swift end, combining masked medical practice with poisoncraft, a noxious aura, and an ultimate suspended-animation mercy.',
    features: wayMercyUaFeatureRefs, source: 'Official', sourceBook: 'Unearthed Arcana 67 - Subclasses, Part 1', edition: 'Both', rulesets: RULESETS,
    isHomebrew: false, isSpellcaster: false, versionNotes: 'Preserved as a distinct official playtest subclass because its mechanics differ materially from both finalized Mercy subclasses.',
  } as any)
  for (const subclass of monkSubclasses) tx = tx.patch(subclass._id, (patch) => patch.set({ rulesets: RULESETS, edition: 'Both', isHomebrew: false }))
  for (const id of subclassFeatureIds) tx = tx.patch(id, (patch) => patch.set({ rulesets: RULESETS, isHomebrew: false }).unset(['ruleset']))
  tx = tx.patch('subclass-warrior-of-the-elements', (patch) => patch.set({
    description: 'Warriors of the Elements tap the Elemental Planes and briefly tame the Elemental Chaos, extending their strikes with elemental force and unleashing destructive bursts, supernatural movement, and shifting resistance.',
    source: 'Official', sourceBook: "Player's Handbook", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Warrior of the Elements mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(ELEMENTS_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Warrior of the Elements mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-warrior-of-mercy', (patch) => patch.set({
    description: 'Warriors of Mercy manipulate the forces of life and death as wandering physicians and faceless bringers of swift relief or final judgment.',
    source: 'Official', sourceBook: "Player's Handbook", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Warrior of Mercy mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(MERCY_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Warrior of Mercy mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-warrior-of-shadow', (patch) => patch.set({
    description: 'Warriors of Shadow harness the Shadowfell for stealth and subterfuge, drawing gloom around themselves, leaping between shadows, and assuming a wraithlike form.',
    source: 'Official', sourceBook: "Player's Handbook", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Warrior of Shadow mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(SHADOW_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Warrior of Shadow mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-warrior-of-the-open-hand', (patch) => patch.set({
    description: 'Warriors of the Open Hand master unarmed combat, learning techniques that addle, push, and topple foes while manipulating their own energy for healing, movement, and lethal vibrations.',
    source: 'Official', sourceBook: "Player's Handbook", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Warrior of the Open Hand mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(OPEN_HAND_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Warrior of the Open Hand mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-astral-self', (patch) => patch.set({
    description: 'A monk of the Way of the Astral Self sees the physical body as an illusion and manifests the true self through spectral arms, visage, body, and a fully awakened astral form.',
    source: 'Official', sourceBook: "Tasha's Cauldron of Everything", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Way of the Astral Self mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(ASTRAL_SELF_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of the Astral Self mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-ascendant-dragon', (patch) => patch.set({
    description: 'Monks of the Way of the Ascendant Dragon align their inner energy with draconic might, transforming their strikes and breath, manifesting spectral wings, and radiating the power of a wyrm in pursuit of spiritual unity with the Material Plane.',
    source: 'Official', sourceBook: "Fizban's Treasury of Dragons", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Way of the Ascendant Dragon mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(ASCENDANT_DRAGON_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of the Ascendant Dragon mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-drunken-master', (patch) => patch.set({
    description: 'Monks of the Way of the Drunken Master conceal a carefully executed dance of blocks, parries, advances, attacks, and retreats behind jerky, unpredictable stumbles, frustrating foes while playing the fool with deliberate skill.',
    source: 'Official', sourceBook: "Xanathar's Guide to Everything", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Way of the Drunken Master mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(DRUNKEN_MASTER_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of the Drunken Master mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-four-elements', (patch) => patch.set({
    description: 'Monks of the Way of the Four Elements align their inner Focus with the forces of creation, learning magical disciplines that bend air, earth, fire, and water as extensions of the body.',
    source: 'Official', sourceBook: "Player's Handbook", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: true,
    versionNotes: 'Complete supplied Way of the Four Elements mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(FOUR_ELEMENTS_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of the Four Elements mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-kensei', (patch) => patch.set({
    description: 'Monks of the Way of the Kensei train until weapons become extensions of the body, treating blade, bow, and other arms as an artist treats a brush: tools for expressing the beauty and precision of martial discipline.',
    source: 'Official', sourceBook: "Xanathar's Guide to Everything", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Way of the Kensei mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(KENSEI_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of the Kensei mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-long-death', (patch) => patch.set({
    description: 'Monks of the Way of the Long Death obsessively study the meaning and mechanics of dying, using knowledge gathered at the moment of death to shape a chilling and deadly martial discipline.',
    source: 'Official', sourceBook: "Sword Coast Adventurer's Guide", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied Way of the Long Death mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(LONG_DEATH_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of the Long Death mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-open-hand', (patch) => patch.set({
    description: 'Monks of the Way of the Open Hand master martial combat, using precise techniques to push and topple opponents, inner Focus to heal their bodies, and advanced meditation to ward away harm.',
    source: 'Official', sourceBook: "Player's Handbook", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: false,
    versionNotes: 'Complete supplied 2014 Way of the Open Hand mechanics enabled for both archive rulesets by owner request; the 2024 Warrior of the Open Hand remains separate.',
  }))
  for (const [id, seed] of Object.entries(WAY_OPEN_HAND_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied 2014 Way of the Open Hand mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-shadow', (patch) => patch.set({
    description: 'Monks of the Way of Shadow prize stealth and subterfuge, serving as secretive spies, assassins, ninjas, and shadowdancers whose monasteries demand discipline and unquestioning discretion.',
    source: 'Official', sourceBook: "Player's Handbook", edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: true,
    versionNotes: 'Complete supplied 2014 Way of Shadow mechanics enabled for both archive rulesets by owner request; the 2024 Warrior of Shadow remains separate.',
  }))
  for (const [id, seed] of Object.entries(WAY_SHADOW_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied 2014 Way of Shadow mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-way-of-the-sun-soul', (patch) => patch.set({
    description: 'Monks of the Way of the Sun Soul channel their own life energy into searing bolts and eruptions of light, using meditation to unleash the indomitable radiance within every living soul.',
    source: 'Official', sourceBook: SUN_SOUL_SOURCE, edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: true,
    versionNotes: 'Complete supplied Way of the Sun Soul mechanics enabled for both archive rulesets by owner request.',
  }))
  for (const [id, seed] of Object.entries(SUN_SOUL_FEATURES)) tx = tx.patch(id, (patch) => patch.set({ name: seed.name, acquiredAtLevel: seed.level, description: seed.description, rulesets: RULESETS, isHomebrew: false, versionNotes: 'Complete supplied Way of the Sun Soul mechanic enabled for both archive rulesets by owner request.' }).unset(['ruleset']))
  tx = tx.patch('subclass-tranquility', (patch) => patch.set({
    description: 'Monks of the Way of Tranquility treat violence as a last resort, using diplomacy, mercy, healing, and supernatural calm to preserve allies and resolve conflict while remaining capable of answering irredeemable cruelty.',
    features: tranquilityFeatureRefs, source: 'Official', sourceBook: 'Unearthed Arcana 24 - Monk', edition: 'Both', rulesets: RULESETS, isHomebrew: false, isSpellcaster: true,
    magicType: 'Focus Magic (Sanctuary)', magicAbility: 'Wisdom', magicDescription: 'Casts Sanctuary on the Monk without material components through Path of Tranquility.',
    versionNotes: 'Corrected malformed feature levels, added the missing Douse the Flames of War feature, and applied the complete supplied playtest mechanics for both archive rulesets.',
  }).unset(['ruleset', 'spells']))
  tx = tx.delete('feature-subclass-tranquility-6-healing-hands')
  tx = tx.delete('feature-subclass-tranquility-11-emissary-of-peace')
  tx = tx.patch('class-monk', (patch) => patch.set({
    description: 'A disciplined martial artist who channels inner Focus into extraordinary speed, defense, movement, and supernatural strikes, transforming body and mind into a living weapon.',
    hitDie: 8, primaryAbility: ['DEX', 'WIS'], savingThrows: ['STR', 'DEX'],
    proficiencies: [
      { _type: 'proficiencyRule', _key: 'monk-weapons', type: 'weapon', mode: 'fixed', weaponOptions: ['Simple Weapons', 'Scimitar', 'Shortsword'], description: 'Simple weapons and martial melee weapons with the Light property' },
      { _type: 'proficiencyRule', _key: 'monk-tools', type: 'tool', mode: 'choice', count: 1, toolOptions: ARTISAN_TOOLS_AND_INSTRUMENTS, description: "Choose one type of artisan's tools or musical instrument" },
      { _type: 'proficiencyRule', _key: 'monk-skills', type: 'skill', mode: 'choice', count: 2, skillOptions: ['Acrobatics', 'Athletics', 'History', 'Insight', 'Religion', 'Stealth'] },
    ],
    startingEquipment: ['Option A: Spear, 5 daggers, the chosen artisan’s tools or musical instrument, an explorer’s pack, and 11 GP', 'Option B: 50 GP'],
    isSpellcaster: false, spellcaster: 'none', features: featureRefs, progression, subclassLevel: 3,
    subclasses: [...new Set([...current.subclassIds, ...ADDITIVE_MONK_SUBCLASS_IDS])].map((id) => ref(id, id.replace(/^subclass-/, ''))),
    source: 'Official', sourceBook: "Player's Handbook", edition: 'Both', rulesets: RULESETS, isHomebrew: false,
    versionNotes: 'All complete Monk core mechanics and every Monk subclass are enabled for both 2014 and 2024 at the archive owner’s request. Five hybrid placeholder features were replaced by the full supplied progression.',
  }).unset(['spellcastingAbility', 'spellLists', 'spells']))
  for (const id of OLD_FEATURE_IDS) tx = tx.delete(id)

  if (!APPLY) { console.log(`Dry run: replace 5 placeholders with ${coreFeatures.length} complete Monk features, add ${progression.length} progression rows, normalize ${monkSubclasses.length} subclasses plus ${subclassFeatureIds.length} existing subclass features to both rulesets, and repair Way of Tranquility to five correctly leveled features.`); return }
  const result = await tx.commit({ visibility: 'sync' })
  const audit = await client.fetch<any>(`*[_id=="class-monk"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,spellcaster,hitDie,primaryAbility,savingThrows,"rulesetCount":count(rulesets),"featureCount":count(features),"progressionCount":count(progression),"subclassCount":count(subclasses),"brokenRefs":count(features[!defined(@->._id)])+count(subclasses[!defined(@->._id)]),"coreFeaturesNotBoth":count(*[_type=="feature" && _id in $coreFeatureIds && count(rulesets)!=2]),"levels":progression[].level,"martialArts":progression[].resources[name=="Martial Arts"][0].value,"focus":progression[].resources[name=="Focus Points"][0].value,"movement":progression[].resources[name=="Unarmored Movement"][0].value,"subclassesNotBoth":count(*[_type=="subclass" && (parentClassId=="monk" || parentClass._ref=="class-monk") && count(rulesets)!=2]),"subclassFeaturesNotBoth":count(*[_type=="feature" && _id in $subclassFeatureIds && count(rulesets)!=2]),"homebrewMonkRecords":count(*[isHomebrew==true && (_id=="class-monk" || (_type=="subclass" && (parentClassId=="monk" || parentClass._ref=="class-monk")) || (_type=="feature" && (_id in $subclassFeatureIds || _id in $coreFeatureIds)))]),"oldFeatures":count(*[_id in $oldIds])}`, { coreFeatureIds, subclassFeatureIds, oldIds: OLD_FEATURE_IDS })
  const problems: string[] = []
  if (audit.source !== 'Official' || audit.sourceBook !== "Player's Handbook" || audit.edition !== 'Both' || audit.isHomebrew || audit.isSpellcaster || audit.spellcaster !== 'none') problems.push('identity/flags')
  if (audit.hitDie !== 8 || audit.primaryAbility.join(',') !== 'DEX,WIS' || audit.savingThrows.join(',') !== 'STR,DEX') problems.push('core traits')
  if (audit.rulesetCount !== 2 || audit.featureCount !== coreFeatures.length || audit.progressionCount !== 20 || audit.subclassCount !== 19 || audit.brokenRefs || audit.coreFeaturesNotBoth) problems.push('references/counts')
  if (audit.levels.join(',') !== progressionRows.map((row) => row[0]).join(',') || audit.martialArts.join(',') !== progressionRows.map((row) => row[2]).join(',') || audit.focus.join(',') !== progressionRows.map((row) => row[3]).join(',') || audit.movement.join(',') !== progressionRows.map((row) => row[4]).join(',')) problems.push('progression')
  if (audit.subclassesNotBoth || audit.subclassFeaturesNotBoth || audit.homebrewMonkRecords || audit.oldFeatures) problems.push('ruleset/homebrew normalization')
  const elementsAudit = await client.fetch<any>(`*[_id=="subclass-warrior-of-the-elements"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (elementsAudit.source !== 'Official' || elementsAudit.sourceBook !== "Player's Handbook" || elementsAudit.edition !== 'Both' || elementsAudit.isHomebrew || elementsAudit.isSpellcaster || elementsAudit.rulesetCount !== 2 || elementsAudit.featureCount !== 5 || elementsAudit.brokenRefs || elementsAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== ELEMENTS_FEATURES[feature._id]?.description)) problems.push('Warrior of the Elements')
  const mercyAudit = await client.fetch<any>(`*[_id=="subclass-warrior-of-mercy"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (mercyAudit.source !== 'Official' || mercyAudit.sourceBook !== "Player's Handbook" || mercyAudit.edition !== 'Both' || mercyAudit.isHomebrew || mercyAudit.isSpellcaster || mercyAudit.rulesetCount !== 2 || mercyAudit.featureCount !== 6 || mercyAudit.brokenRefs || mercyAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== MERCY_FEATURES[feature._id]?.description)) problems.push('Warrior of Mercy')
  const shadowAudit = await client.fetch<any>(`*[_id=="subclass-warrior-of-shadow"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (shadowAudit.source !== 'Official' || shadowAudit.sourceBook !== "Player's Handbook" || shadowAudit.edition !== 'Both' || shadowAudit.isHomebrew || shadowAudit.isSpellcaster || shadowAudit.rulesetCount !== 2 || shadowAudit.featureCount !== 4 || shadowAudit.brokenRefs || shadowAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== SHADOW_FEATURES[feature._id]?.description)) problems.push('Warrior of Shadow')
  const openHandAudit = await client.fetch<any>(`*[_id=="subclass-warrior-of-the-open-hand"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (openHandAudit.source !== 'Official' || openHandAudit.sourceBook !== "Player's Handbook" || openHandAudit.edition !== 'Both' || openHandAudit.isHomebrew || openHandAudit.isSpellcaster || openHandAudit.rulesetCount !== 2 || openHandAudit.featureCount !== 4 || openHandAudit.brokenRefs || openHandAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== OPEN_HAND_FEATURES[feature._id]?.description)) problems.push('Warrior of the Open Hand')
  const astralSelfAudit = await client.fetch<any>(`*[_id=="subclass-astral-self"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (astralSelfAudit.source !== 'Official' || astralSelfAudit.sourceBook !== "Tasha's Cauldron of Everything" || astralSelfAudit.edition !== 'Both' || astralSelfAudit.isHomebrew || astralSelfAudit.isSpellcaster || astralSelfAudit.rulesetCount !== 2 || astralSelfAudit.featureCount !== 4 || astralSelfAudit.brokenRefs || astralSelfAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== ASTRAL_SELF_FEATURES[feature._id]?.description)) problems.push('Way of the Astral Self')
  const ascendantDragonAudit = await client.fetch<any>(`*[_id=="subclass-ascendant-dragon"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (ascendantDragonAudit.source !== 'Official' || ascendantDragonAudit.sourceBook !== "Fizban's Treasury of Dragons" || ascendantDragonAudit.edition !== 'Both' || ascendantDragonAudit.isHomebrew || ascendantDragonAudit.isSpellcaster || ascendantDragonAudit.rulesetCount !== 2 || ascendantDragonAudit.featureCount !== 5 || ascendantDragonAudit.brokenRefs || ascendantDragonAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== ASCENDANT_DRAGON_FEATURES[feature._id]?.description)) problems.push('Way of the Ascendant Dragon')
  const drunkenMasterAudit = await client.fetch<any>(`*[_id=="subclass-drunken-master"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (drunkenMasterAudit.source !== 'Official' || drunkenMasterAudit.sourceBook !== "Xanathar's Guide to Everything" || drunkenMasterAudit.edition !== 'Both' || drunkenMasterAudit.isHomebrew || drunkenMasterAudit.isSpellcaster || drunkenMasterAudit.rulesetCount !== 2 || drunkenMasterAudit.featureCount !== 5 || drunkenMasterAudit.brokenRefs || drunkenMasterAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== DRUNKEN_MASTER_FEATURES[feature._id]?.description)) problems.push('Way of the Drunken Master')
  const fourElementsAudit = await client.fetch<any>(`*[_id=="subclass-four-elements"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (fourElementsAudit.source !== 'Official' || fourElementsAudit.sourceBook !== "Player's Handbook" || fourElementsAudit.edition !== 'Both' || fourElementsAudit.isHomebrew || !fourElementsAudit.isSpellcaster || fourElementsAudit.rulesetCount !== 2 || fourElementsAudit.featureCount !== 4 || fourElementsAudit.brokenRefs || fourElementsAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== FOUR_ELEMENTS_FEATURES[feature._id]?.description)) problems.push('Way of the Four Elements')
  const kenseiAudit = await client.fetch<any>(`*[_id=="subclass-kensei"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (kenseiAudit.source !== 'Official' || kenseiAudit.sourceBook !== "Xanathar's Guide to Everything" || kenseiAudit.edition !== 'Both' || kenseiAudit.isHomebrew || kenseiAudit.isSpellcaster || kenseiAudit.rulesetCount !== 2 || kenseiAudit.featureCount !== 4 || kenseiAudit.brokenRefs || kenseiAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== KENSEI_FEATURES[feature._id]?.description)) problems.push('Way of the Kensei')
  const longDeathAudit = await client.fetch<any>(`*[_id=="subclass-long-death"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (longDeathAudit.source !== 'Official' || longDeathAudit.sourceBook !== "Sword Coast Adventurer's Guide" || longDeathAudit.edition !== 'Both' || longDeathAudit.isHomebrew || longDeathAudit.isSpellcaster || longDeathAudit.rulesetCount !== 2 || longDeathAudit.featureCount !== 4 || longDeathAudit.brokenRefs || longDeathAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== LONG_DEATH_FEATURES[feature._id]?.description)) problems.push('Way of the Long Death')
  const wayMercyAudit = await client.fetch<any>(`*[_id==$id][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,parentClassId,"parentRef":parentClass._ref,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`, { id: WAY_MERCY_ID })
  if (wayMercyAudit.source !== 'Official' || wayMercyAudit.sourceBook !== "Tasha's Cauldron of Everything" || wayMercyAudit.edition !== 'Both' || wayMercyAudit.isHomebrew || wayMercyAudit.isSpellcaster || wayMercyAudit.parentClassId !== 'monk' || wayMercyAudit.parentRef !== 'class-monk' || wayMercyAudit.rulesetCount !== 2 || wayMercyAudit.featureCount !== 6 || wayMercyAudit.brokenRefs || wayMercyAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== WAY_MERCY_FEATURES[feature._id]?.description)) problems.push('Way of Mercy')
  const wayOpenHandAudit = await client.fetch<any>(`*[_id=="subclass-open-hand"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (wayOpenHandAudit.source !== 'Official' || wayOpenHandAudit.sourceBook !== "Player's Handbook" || wayOpenHandAudit.edition !== 'Both' || wayOpenHandAudit.isHomebrew || wayOpenHandAudit.isSpellcaster || wayOpenHandAudit.rulesetCount !== 2 || wayOpenHandAudit.featureCount !== 4 || wayOpenHandAudit.brokenRefs || wayOpenHandAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== WAY_OPEN_HAND_FEATURES[feature._id]?.description)) problems.push('Way of the Open Hand')
  const wayShadowAudit = await client.fetch<any>(`*[_id=="subclass-shadow"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (wayShadowAudit.source !== 'Official' || wayShadowAudit.sourceBook !== "Player's Handbook" || wayShadowAudit.edition !== 'Both' || wayShadowAudit.isHomebrew || !wayShadowAudit.isSpellcaster || wayShadowAudit.rulesetCount !== 2 || wayShadowAudit.featureCount !== 4 || wayShadowAudit.brokenRefs || wayShadowAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== WAY_SHADOW_FEATURES[feature._id]?.description)) problems.push('Way of Shadow')
  const sunSoulAudit = await client.fetch<any>(`*[_id=="subclass-way-of-the-sun-soul"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (sunSoulAudit.source !== 'Official' || sunSoulAudit.sourceBook !== SUN_SOUL_SOURCE || sunSoulAudit.edition !== 'Both' || sunSoulAudit.isHomebrew || !sunSoulAudit.isSpellcaster || sunSoulAudit.rulesetCount !== 2 || sunSoulAudit.featureCount !== 4 || sunSoulAudit.brokenRefs || sunSoulAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== SUN_SOUL_FEATURES[feature._id]?.description)) problems.push('Way of the Sun Soul')
  const ascendantDragonUaAudit = await client.fetch<any>(`*[_id==$id][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,parentClassId,"parentRef":parentClass._ref,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`, { id: ASCENDANT_DRAGON_UA_ID })
  if (ascendantDragonUaAudit.source !== 'Official' || ascendantDragonUaAudit.sourceBook !== 'Unearthed Arcana 75 - Subclasses, Part 5' || ascendantDragonUaAudit.edition !== 'Both' || ascendantDragonUaAudit.isHomebrew || ascendantDragonUaAudit.isSpellcaster || ascendantDragonUaAudit.parentClassId !== 'monk' || ascendantDragonUaAudit.parentRef !== 'class-monk' || ascendantDragonUaAudit.rulesetCount !== 2 || ascendantDragonUaAudit.featureCount !== 5 || ascendantDragonUaAudit.brokenRefs || ascendantDragonUaAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== ASCENDANT_DRAGON_UA_FEATURES[feature._id]?.description)) problems.push('Way of the Ascendant Dragon (UA)')
  const astralSelfUaAudit = await client.fetch<any>(`*[_id==$id][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,parentClassId,"parentRef":parentClass._ref,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`, { id: ASTRAL_SELF_UA_ID })
  if (astralSelfUaAudit.source !== 'Official' || astralSelfUaAudit.sourceBook !== 'Unearthed Arcana 60 - Barbarian and Monk' || astralSelfUaAudit.edition !== 'Both' || astralSelfUaAudit.isHomebrew || astralSelfUaAudit.isSpellcaster || astralSelfUaAudit.parentClassId !== 'monk' || astralSelfUaAudit.parentRef !== 'class-monk' || astralSelfUaAudit.rulesetCount !== 2 || astralSelfUaAudit.featureCount !== 4 || astralSelfUaAudit.brokenRefs || astralSelfUaAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== ASTRAL_SELF_UA_FEATURES[feature._id]?.description)) problems.push('Way of the Astral Self (UA)')
  const kenseiUaAudit = await client.fetch<any>(`*[_id==$id][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,parentClassId,"parentRef":parentClass._ref,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`, { id: KENSEI_UA_ID })
  if (kenseiUaAudit.source !== 'Official' || kenseiUaAudit.sourceBook !== 'Unearthed Arcana 24 - Monk' || kenseiUaAudit.edition !== 'Both' || kenseiUaAudit.isHomebrew || kenseiUaAudit.isSpellcaster || kenseiUaAudit.parentClassId !== 'monk' || kenseiUaAudit.parentRef !== 'class-monk' || kenseiUaAudit.rulesetCount !== 2 || kenseiUaAudit.featureCount !== 4 || kenseiUaAudit.brokenRefs || kenseiUaAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== KENSEI_UA_FEATURES[feature._id]?.description)) problems.push('Kensei (UA)')
  const wayMercyUaAudit = await client.fetch<any>(`*[_id==$id][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,parentClassId,"parentRef":parentClass._ref,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`, { id: WAY_MERCY_UA_ID })
  if (wayMercyUaAudit.source !== 'Official' || wayMercyUaAudit.sourceBook !== 'Unearthed Arcana 67 - Subclasses, Part 1' || wayMercyUaAudit.edition !== 'Both' || wayMercyUaAudit.isHomebrew || wayMercyUaAudit.isSpellcaster || wayMercyUaAudit.parentClassId !== 'monk' || wayMercyUaAudit.parentRef !== 'class-monk' || wayMercyUaAudit.rulesetCount !== 2 || wayMercyUaAudit.featureCount !== 6 || wayMercyUaAudit.brokenRefs || wayMercyUaAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== WAY_MERCY_UA_FEATURES[feature._id]?.description)) problems.push('Way of Mercy (UA)')
  const tranquilityAudit = await client.fetch<any>(`*[_id=="subclass-tranquility"][0]{source,sourceBook,edition,isHomebrew,isSpellcaster,magicType,magicAbility,"rulesetCount":count(rulesets),"featureCount":count(features),"brokenRefs":count(features[!defined(@->._id)]),"features":features[]->{_id,name,acquiredAtLevel,description,isHomebrew,"rulesetCount":count(rulesets)}}`)
  if (tranquilityAudit.source !== 'Official' || tranquilityAudit.sourceBook !== 'Unearthed Arcana 24 - Monk' || tranquilityAudit.edition !== 'Both' || tranquilityAudit.isHomebrew || !tranquilityAudit.isSpellcaster || tranquilityAudit.magicType !== 'Focus Magic (Sanctuary)' || tranquilityAudit.magicAbility !== 'Wisdom' || tranquilityAudit.rulesetCount !== 2 || tranquilityAudit.featureCount !== 5 || tranquilityAudit.brokenRefs || tranquilityAudit.features.some((feature: any) => feature.isHomebrew || feature.rulesetCount !== 2 || feature.description !== TRANQUILITY_FEATURES[feature._id]?.description)) problems.push('Way of Tranquility')
  if (problems.length) throw new Error(`Monk audit failed: ${problems.join('; ')} :: ${JSON.stringify(audit)}`)
  console.log(`Applied ${result.results.length} mutations. Verification: ${JSON.stringify(audit)}`)
}

run().catch((error) => { console.error(error); process.exit(1) })
