import { sourceField, sourceBookField, editionField, versionField, rulesetField, rulesetsField, isHomebrewField, versionNotesField } from './common/source'

export default {
    name: 'spell',
    title: 'Spell',
    type: 'document',
    fields: [
        {
            name: 'name',
            title: 'Name',
            type: 'string',
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'slug',
            title: 'Slug (ID)',
            type: 'slug',
            options: {
                source: 'name',
                maxLength: 96,
            },
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'level',
            title: 'Level',
            type: 'number',
            validation: (Rule: any) => Rule.required().min(0).max(9),
        },
        {
            name: 'school',
            title: 'School',
            type: 'reference',
            to: [{ type: 'magicSchool' }],
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'legacySchoolName',
            title: 'Legacy School Name',
            type: 'string',
            hidden: true,
            description: 'Original school text retained by the reference migration.',
        },
        {
            name: 'castingTime',
            title: 'Casting Time',
            type: 'string',
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'range',
            title: 'Range',
            type: 'string',
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'components',
            title: 'Components',
            type: 'object',
            fields: [
                { name: 'verbal', title: 'Verbal (V)', type: 'boolean', initialValue: false },
                { name: 'somatic', title: 'Somatic (S)', type: 'boolean', initialValue: false },
                { name: 'material', title: 'Material (M)', type: 'boolean', initialValue: false },
                {
                    name: 'materialDescription',
                    title: 'Material Component Details',
                    type: 'text',
                    rows: 2,
                    hidden: ({ parent }: any) => !parent?.material,
                },
            ],
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'materialCost',
            title: 'Legacy Material Component Details',
            type: 'text',
            rows: 2,
            hidden: true,
            description: 'Preserved for older records. New details live inside Components.',
        },
        {
            name: 'duration',
            title: 'Duration',
            type: 'string',
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'concentration',
            title: 'Concentration',
            type: 'boolean',
            initialValue: false,
        },
        {
            name: 'ritual',
            title: 'Ritual',
            type: 'boolean',
            initialValue: false,
        },
        {
            name: 'description',
            title: 'Description',
            type: 'text',
            rows: 10,
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'image',
            title: 'Image',
            type: 'image',
            options: {
                hotspot: true,
            },
        },
        {
            name: 'higherLevels',
            title: 'At Higher Levels',
            type: 'text',
        },
        {
            name: 'classes',
            title: 'Classes',
            type: 'array',
            of: [{ type: 'string' }],
            description: 'IDs of classes that can cast this spell',
        },
        {
            name: 'subclasses',
            title: 'Granted by Subclasses',
            type: 'array',
            of: [{ type: 'reference', to: [{ type: 'subclass' }] }],
            description: 'Reverse links maintained from subclass spell grants by the SRD spell sync.',
        },
        sourceField,
        sourceBookField,
        editionField,
        versionField,
        rulesetsField,
        rulesetField,
        isHomebrewField,
        versionNotesField,
    ],
}
